//
// Generated by afu_json_mgr from ../../hw/afu.json
//

`ifndef __AFU_JSON_INFO__
`define __AFU_JSON_INFO__

`define AFU_ACCEL_NAME "afu"
`define AFU_ACCEL_UUID 128'hB2AD32D2_3B1E_4E59_AF4B_4D2018494533
`define AFU_IMAGE_POWER 0
`define AFU_TOP_IFC "ccip_std_afu"

`endif // __AFU_JSON_INFO__
